# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
command_timeout = 200

[git_status]
conflicted = "!"
untracked = "u"
stashed = "$"
modified = "m"
staged = ""
renamed = "r"
deleted = "d"

[hostname]
ssh_symbol = ""